name: Dream Vacation App

on : [push]

jobs:
    backend:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v5
          - uses: actions/setup-node@v4
            with:
                node-version: '20'
          - name: Install dependencies
            run: npm install
            working-directory: "./backend"

    frontend:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v5
          - uses: actions/setup-node@v4
            with:
                node-version: '20'
          - name: Install dependencies
            run: npm install
            working-directory: "./frontend"

          - name: Fix build
            run: export NODE_OPTIONS=--openssl-legacy-provider
            working-directory: "./frontend"

          - name: Build
            run: npm run build
            working-directory: "./frontend"

          - name: Run test
            run: npm run test
            working-directory: "./frontend"

         