name: Dream Vacation App

on :
    push:
        branches: [dev, staging, main]

jobs:
    backend:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v5
          - uses: actions/setup-node@v4
            with:
                node-version: '20'
          - name: Install dependencies
            run: npm install
            working-directory: "./backend"

    frontend:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v5
          - uses: actions/setup-node@v4
            with:
                node-version: '20'
          - name: Install dependencies
            run: npm install
            working-directory: "./frontend"

          - name: Build
            run: export NODE_OPTIONS=--openssl-legacy-provider npm run build
            working-directory: "./frontend"

          - name: Run test
            run: npm run test -- --passWithNoTests
            working-directory: "./frontend"

         